initStore([
  {
    id: 0,
    title: 'Hogwarts Legacy (PC/PS5/Xbox)',
    description: 'Explore the Wizarding World like never before in this open-world action RPG set in the 1800s.',
    price: 69.99,
    discountPrice: 54.99,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Gran Turismo 7 (PS5)',
    description: 'Master the art of racing with photorealistic visuals, realistic driving physics, and hundreds of cars.',
    price: 59.99,
    discountPrice: 49.99,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'Alan Wake 2 (PC/PS5/Xbox)',
    description: 'A psychological horror thriller that blurs the lines between reality and nightmare.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'Final Fantasy XVI (PS5)',
    description: 'Experience a dark fantasy epic with cinematic combat and an emotional story.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Baldur’s Gate 3 (PC/PS5)',
    description: 'A deep role-playing experience rooted in Dungeons & Dragons with turn-based combat.',
    price: 59.99,
    discountPrice: 49.99,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Spider-Man 2 (PS5)',
    description: 'Swing across New York as Peter Parker and Miles Morales in this high-action superhero sequel.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'images/service-6.jpg',
  },
]);
